apiVersion: v2
name: wazuh-agent
description: Wazuh Agent Helm chart for Kubernetes
type: application
version: "4.12.1"
appVersion: "4.12.0"
dependencies:
  - name: common
    version: 2.30.0
    repository: oci://registry-1.docker.io/bitnamicharts
maintainers:
  - name: KylianLeSaux
    email: kylian.le-saux@avisto.com
annotations:
  artifacthub.io/signKey: |
    fingerprint: AF455B903BFED8363C003F9A5E2474CA7617EC66
    url: https://keybase.io/avistotelecom/pgp_keys.asc
