apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-api-cred
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.agent.labels .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.agent.configuration.username | quote }}
  password: {{ .Values.agent.configuration.password | quote }}
