apiVersion: v2
name: kubebrowser
description: Allow whitelisted people to access your kubeconfigs
type: application
version: "1.1.6"
appVersion: "0.8.3"
dependencies:
  - name: common
    version: 2.30.0
    repository: oci://registry-1.docker.io/bitnamicharts
maintainers:
  - name: Brawdunoir
    email: yann.lacroix@avisto.com
icon: https://raw.githubusercontent.com/AvistoTelecom/kubebrowser/refs/tags/0.6.0/docs/public/logo_light.svg
annotations:
  artifacthub.io/signKey: |
    fingerprint: AF455B903BFED8363C003F9A5E2474CA7617EC66
    url: https://keybase.io/avistotelecom/pgp_keys.asc
