name: Helm Chart Test

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Set up Helm
        uses: azure/setup-helm@v4
      - name: Find changed charts
        id: changed
        run: |
          git fetch origin ${{ github.base_ref }}
          echo "charts=$(git diff --name-only origin/${{ github.base_ref }} | grep '^charts/[^/\n]*/' | cut -d/ -f2 | sort -u | xargs)" >> $GITHUB_OUTPUT
      - name: Install and test changed charts
        if: steps.changed.outputs.charts != ''
        run: |
          for chart in ${{ steps.changed.outputs.charts }}; do
            echo "Testing chart: $chart"
            helm dependency update charts/$chart || true
            helm install --wait --generate-name charts/$chart
            helm test $(helm list -q | grep $chart)
            helm uninstall $(helm list -q | grep $chart)
          done
